var browser={name:null,platform:null,offline:!1,prefix:null,detect:function(){var a=navigator.userAgent.toLowerCase(),b=a.match(/(opera|ie|firefox|chrome|crios|safari)/);null===b?this.name="Safari":"opera"===b[1]?this.name="Opera":"ie"===b[1]?this.name="IE":"firefox"===b[1]?this.name="Firefox":"chrome"===b[1]?this.name="Chrome":"crios"===b[1]?this.name="Chrome":"safari"===b[1]&&(this.name="Safari");a.match(/(?:fvxhtml5offline)/)&&(this.offline=!0);this.platform="Android";a.match(/(?:windows nt)/)&&
(this.platform="Intel");a.match(/(?:tablet pc)/)&&(this.platform="Surface");a.match(/(?:media center pc)/)&&(this.platform="Intel");a.match(/(?:intel mac)/)&&(this.platform="Intel");a.match(/ip(?:ad|od|hone)/)&&(this.platform="iOS");a.match(/(?:ios)/)&&(this.platform="iOS");a.match(/(?:webos|android|bada|symbian|palm|blackberry)/)&&(this.platform="Android");this.prefix="";"Opera"===this.name?this.prefix="-o-":"Safari"===this.name?this.prefix="-webkit-":"Chrome"===this.name?this.prefix="-webkit-":
"Firefox"===this.name?this.prefix="-moz-":"IE"===this.name&&(this.prefix="-ms-")}},device={name:"",is_it_in_iframe:!1,proportionally__counter:0,width:function(){if(this.is_it_in_iframe||"undefined"!=typeof window.innerWidth&&0!=window.innerWidth)return window.innerWidth;if("undefined"!=typeof document.body.clientWidth&&0!=document.body.clientWidth)return document.body.clientWidth;if("undefined"!=typeof document.body.offsetWidth&&0!=document.body.offsetWidth)return document.body.offsetWidth;screen.width},
height:function(){return this.is_it_in_iframe?window.innerHeight:"undefined"!=typeof window.innerHeight&&0!=window.innerHeight?window.innerHeight:"undefined"!=typeof document.body.clientHeight&&0!=document.body.clientHeight?document.body.clientHeight:"undefined"!=typeof document.body.offsetHeight&&0!=document.body.offsetHeight?document.body.offsetHeight:Math.round(this.width()/screen.width*screen.height)},detect:function(){(this.is_it_in_iframe=window.location==window.parent.location?!1:!0)?"Intel"===
browser.platform?this.name="Intel":"Android"===browser.platform?this.name="Android":"iOS"===browser.platform&&(this.name="iPad"):"Intel"===browser.platform?this.name="Intel":"Surface"===browser.platform?this.name="Surface":"Android"===browser.platform?this.name=320>=Math.min(window.innerWidth,window.innerHeight)?"GalaxyS2":360>=Math.min(window.innerWidth,window.innerHeight)?"GalaxyS3":"Android":"iOS"===browser.platform&&(this.name=320>=Math.min(window.innerWidth,window.innerHeight)?"iPhone":"iPad")}},
observer={getOrientation:function(){if("Surface"===browser.platform)return"Landscape";if("iOS"===browser.platform)if(device.is_it_in_iframe){if(device.width()>device.height())return"Landscape";if(device.width()<device.height())return"Portrait"}else{if(0===Math.abs(window.orientation)||180===Math.abs(window.orientation))return"Portrait";if(90===Math.abs(window.orientation)||-90===Math.abs(window.orientation))return"Landscape"}else{if(device.width()>device.height())return"Landscape";if(device.width()<
device.height())return"Portrait"}}},synchronizer={since_delay:0,delayOrientationChange_counter:0,delayResize_counter:0,resizing:null,device_width:0,device_height:0,delayOrientationChange:function(){this.delayOrientationChange_counter++;var a=this;setTimeout(function(){a.delayOrientationChange_()},300)},delayOrientationChange_:function(){if(1<this.delayOrientationChange_counter)this.delayOrientationChange_counter--;else{this.delayOrientationChange_counter=0;if(("GalaxyS2"===device.name||"GalaxyS3"===
device.name)&&null==this.resizing){var a=this;this.resizing=window.setInterval(function(){a.device_width!=device.width()&&a.device_height!=device.height()&&(a.device_width=device.width(),a.device_height=device.height(),a.delayResize())},300)}this.delayOrientationChange__()}},delayOrientationChange__:function(){if(4500>this.since_delay){this.since_delay+=300;var a=this;setTimeout(function(){a.delayOrientationChange__()},300)}else this.since_delay=0,$(document).trigger("orientationChange")},delayResize:function(){this.delayResize_counter++;
var a=this;setTimeout(function(){a.delayResize_()},3E3)},delayResize_:function(){1<this.delayResize_counter?this.delayResize_counter--:(this.delayResize_counter=0,this.since_delay=4500,window.clearInterval(this.resizing),this.resizing=null)},initialize:function(){if("Android"===browser.platform){var a=this;window.addEventListener("orientationchange",function(){a.delayOrientationChange()},!1);"GalaxyS2"!==device.name&&"GalaxyS3"!==device.name&&window.addEventListener("resize",function(){a.delayResize()},
!1)}else window.addEventListener("orientationchange",function(){$(document).trigger("orientationChange")},!1)}};