window.Utility={crossover:null,getParameter:function(a){a=(new RegExp("[\\?&]"+a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]")+"=([^&#]*)")).exec(window.location.search);return null==a?null:decodeURIComponent(a[1].replace(/\+/g," "))},fall:function(a,b){a.stopPropagation();a.cancelBubble=!0;return b?(a.preventDefault(),!1):!0},isItTransparent:function(a){a=a.getContext("2d").getImageData(0,0,a.width,a.height);for(var b=0;b<a.data.length;b+=4)if(0!=a.data[b+3]&&(0!=a.data[b]||0!=a.data[b+1]||0!=a.data[b+
2]))return!1;return!0},textToUTF8Byte:function(a){for(var b=[],c=0;c<a.length;c++){var d=this.charToCodePoint(a,c);!1!==d&&this.charToUTF8Byte(d,b)}return b},charToUTF8Byte:function(a,b){127>=a?b.push(a):2047>=a?b.push(192|a>>6,128|a&63):65535>=a?b.push(224|a>>12,128|a>>6&63,128|a&63):2097151>=a&&b.push(240|a>>18,128|a>>12&63,128|a>>6&63,128|a&63)},charToCodePoint:function(a,b){b=b||0;var c=a.charCodeAt(b),d;return 55296<=c&&56319>=c?(d=a.charCodeAt(b+1),isNaN(d)?!1:1024*(c-55296)+(d-56320)+65536):
56320<=c&&57343>=c?!1:c},filterFoul:function(a){for(var b="",c=0;c<a.length;c++)!1!==this.charToCodePoint(a,c)&&(b+=a.charAt(c));return b},realLength:function(a){for(var b=0,c=0;c<a.length;){var d=this.charToCodePoint(a,c);if(!1!==d){var e=[];this.charToUTF8Byte(d,e);1<e.length?b+=2.1:(d=a.charAt(c),isNaN(1*d)?d==d.toUpperCase()?b="iPhone"==device.name||"GalaxyS2"==device.name||"GalaxyS3"==device.name?b+1.5:b+1.2:d==d.toLowerCase()&&b++:b+=1.2)}c++}return Math.round(b)},x:function(a){return"undefined"!=
typeof a.pageX?a.pageX:"undefined"!=typeof a.clientX?a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft:-1},y:function(a){return"undefined"!=typeof a.pageY?a.pageY:"undefined"!=typeof a.clientY?a.clientY+document.body.scrollTop+document.documentElement.scrollTop:-1},translate:function(a,b,c){"undefined"!=typeof a.pageX?a.pageX+=b:"undefined"!=typeof a.clientX&&(a.clientX+=b);"undefined"!=typeof a.pageY?a.pageY+=c:"undefined"!=typeof a.clientY&&(a.clientY+=c);return a},toHexadecimal:function(a){a=
Math.abs(a);var b=String(a%16);"10"==b?b="A":"11"==b?b="B":"12"==b?b="C":"13"==b?b="D":"14"==b?b="E":"15"==b&&(b="F");return 0==Math.floor(a/16)?b:this.toHexadecimal(Math.floor(a/16))+b},toDecimal:function(a){var b=a.slice(0,1);"A"==b?b="10":"B"==b?b="11":"C"==b?b="12":"D"==b?b="13":"E"==b?b="14":"F"==b&&(b="15");return 1==a.length?parseInt(b):parseInt(b)*Math.pow(16,a.length-1)+this.toDecimal(a.slice(1))},decToHexRGB:function(a){if("X"==a.substring(0,1)||"$"==a.substring(0,1))a=a.substring(1);else{var b=
1;0<parseInt(a)&&(b=Math.floor(Math.log(parseInt(a))/Math.log(16))+1);xx=window.Utility.toHexadecimal(parseInt(a));for(a="";6>b;b++)a+="0";a+=xx}return"#"+a.substring(4,5)+a.substring(5,6)+a.substring(2,3)+a.substring(3,4)+a.substring(0,1)+a.substring(1,2)},parseURI:function(a){return(a=String(a).replace(/^\s+|\s+$/g,"").match(/^([^:\/?#]+:)?(\/\/(?:[^:@]*(?::[^:@]*)?@)?(([^:\/?#]*)(?::(\d*))?))?([^?#]*)(\?[^#]*)?(#[\s\S]*)?/))?{href:a[0]||"",protocol:a[1]||"",authority:a[2]||"",host:a[3]||"",hostname:a[4]||
"",port:a[5]||"",pathname:a[6]||"",search:a[7]||"",hash:a[8]||""}:null},removeDotSegments:function(a){var b=[];a.replace(/^(\.\.?(\/|$))+/,"").replace(/\/(\.(\/|$))+/g,"/").replace(/\/\.\.$/,"/../").replace(/\/?[^\/]*/g,function(a){"/.."===a?b.pop():b.push(a)});return b.join("").replace(/^\//,"/"===a.charAt(0)?"/":"")},absolutizeURL:function(a,b){if(window.Personalize.behind_barrier)return a+b;b=this.parseURI(b||"");a=this.parseURI(a||"");return b&&a?(b.protocol||a.protocol)+(b.protocol||b.authority?
b.authority:a.authority)+this.removeDotSegments(b.protocol||b.authority||"/"===b.pathname.charAt(0)?b.pathname:b.pathname?(a.authority&&!a.pathname?"/":"")+a.pathname.slice(0,a.pathname.lastIndexOf("/")+1)+b.pathname:a.pathname)+(b.protocol||b.authority||b.pathname?b.search:b.search||a.search)+b.hash:null},transcendEvent:function(a,b,c){var d=a.createEvent("HTMLEvents");d.initEvent(c,!0,!0);a.elementFromPoint(this.x(b),this.y(b)).dispatchEvent(d)},clientWidth:function(){return window.HighDefinition.is_shown?
window.Install.magnify_width:window.Install.page_width},clientHeight:function(){return window.HighDefinition.is_shown?window.Install.magnify_height:window.Install.page_height},measureText:function(a,b){var c=(this.measureText.canvas||(this.measureText.canvas=document.createElement("canvas"))).getContext("2d");c.font=b;return c.measureText(a).width},paragraph:function(a,b,c,d){var e=[];for(e.push(a);;){a=0;var g=-1,f=e.pop();if(this.measureText(f,b)<=c){e.push(f.replace(RegExp("\n","g"),d));break}for(;a<
f.length;){" "==f.substring(a,a+1)&&(g=a);if("\n"==f.substring(a,a+1)){g=a;break}if(this.measureText(f.substring(0,a),b)>c)break;a++}-1==g?(e.push(f.substring(0,a-1)),e.push(f.substring(a-1))):(e.push(f.substring(0,g)),e.push(f.substring(g+1)))}return e.join(d)},getCurrentDate:function(){var a=new Date;return"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")[a.getMonth()]+" "+a.getDate()+", "+a.getFullYear()},getCurrentTime:function(){var a=new Date;return a.getHours()+":"+a.getMinutes()+
":"+a.getSeconds()},cached:[],cached_i:0,cacheAnImageOnLoad:function(){window.Utility.cacheAnImageOnLoad_flag=!1},cacheAnImage:function(a){this.cached[this.cached_i]=new Image;this.cacheAnImageOnLoad_flag=!0;this.cached[this.cached_i].onLoad=this.cacheAnImageOnLoad();do this.cached[this.cached_i].src=a;while(this.cacheAnImageOnLoad_flag);this.cached_i++;if(200<this.cached_i){for(a=0;a<this.cached_i;a++)this.cached[a]=null;this.cached=[];this.cached_i=0}},repelFrom:function(){$(".Typography").css("left",
"0px").css("top","0px").html("").hide()},appealTo:function(a,b,c,d){var e=0,g=0,f=!0;"undefined"==typeof $(".Tip")[0]&&($("body").append($('<div class="Typography"></div>')),$(".Typography").css("font-size",window.Install.font_size+"px"));g=Math.ceil(window.Utility.realLength(a.toString())*window.Install.font_size/2);"Left"==d?0>b-48-g?(e=8+g,b+e>window.Install.client_width&&(f=!1)):e=-48:"Right"==d&&(b+32+g>window.Install.client_width?(e=-8-g,0>b+e&&(f=!1)):e=32);c+8+26>window.Install.client_height?
(g=-26,0>c+g&&(f=!1)):g=8;f&&$(".Typography").css("left",b+e+"px").css("top",c+g+"px").html("<table><tr><td nowrap>"+a+"</td></tr></table>").show()},devicePixelRatio:function(){var a=document.createElement("canvas").getContext("2d");return(window.devicePixelRatio||1)/(a.webkitBackingStorePixelRatio||a.mozBackingStorePixelRatio||a.msBackingStorePixelRatio||a.oBackingStorePixelRatio||a.backingStorePixelRatio||1)},traverse:function(a,b,c){"undefined"!=typeof a[c]&&("string"!=typeof a&&"string"==typeof a[c]&&
a[c]!=a[c].split(b)&&(a[c]=a[c].split(b)),$.isArray(a[c])&&this.traverse(a[c],b,0),$.isArray(a)&&this.traverse(a,b,c+1))},demolish:function(a){return a.reduce(function(a,c){return a.concat($.isArray(c)?window.Utility.demolish(c):c)},[])},split:function(a,b){for(var c=[],d="",e=0;e<a.length;){var g=this.charToCodePoint(a,e);if(!1!==g){var f=[];this.charToUTF8Byte(g,f);1<f.length?(c.push(d),d="",c.push(a.substring(e,e+1))):d+=a.substring(e,e+1)}e++}""!=d&&c.push(d);d=[];for(e=g=0;e<c.length;e++)if(1==
c[e].length)d[g]=c[e],g++;else{for(var h=[c[e]],f=0;f<b.length;f++)this.traverse(h,b[f],0);h=this.demolish(h);for(f=0;f<h.length;f++)""!=h[f]&&(d[g]=h[f],g++)}return d},polish:function(a,b){for(var c=this.split(a,b),d=c.length-1;0<=d;d--)""!=c[d]&&(a=c[d]);return a}};